version: '3.9'

services:

  questao5-webapi:
    ports:
      - 5072:5072
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:gfmaurila
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:gfmaurila
